### ISSUE TITLE
Huge RAM usage

### ISSUE THREAD

**Issue by kozross** [akrennmair/newsbeuter#220] opened 2015-11-26 23:41 UTC
Not exactly a bug, but more of a 'why on earth' question. Currently, my newsbeuter is eating over 1G of RAM, which I find surprising of a terminal application. Why so much?

**Comment by Minoru** [comment] 2015-12-06 15:00
Sorry for delayed reply! I somehow missed the notification about new issue.

What version of Newsbeuter are you running? I suspect you've run into #119. Can you build from source (from the current HEAD) and report back?

**Comment by kozross** [comment] 2015-12-07 13:53
I'm on 2.9. I'll rebuild and get back to you to see if this continues to occur.

**Comment by NoSuck** [comment] 2015-12-12 15:11
This issue affects me as well, with the following installation.  I will try the latest HEAD and report back.

```
Compilation date/time: Dec  7 2015 04:47:17
System: Linux 4.2.5-1-ARCH (x86_64)
Compiler: g++ 5.3.0
ncurses: ncurses 6.0.20150808 (compiled with 6.0)
libcurl: libcurl/7.45.0 OpenSSL/1.0.2e zlib/1.2.8 libidn/1.32 libssh2/1.6.0 (compiled with 7.46.0)
SQLite: 3.9.2 (compiled with 3.9.2)
libxml2: compiled with 2.9.2
```

**Comment by NoSuck** [comment] 2015-12-13 07:48
The issue seems to have been resolved in the latest 2.10 pull from git.

**Comment by Minoru** [comment] 2015-12-13 17:34
Yay, exactly what I hoped for! But let's see what @kozross say; maybe he bumped into a different issue, after all.

**Comment by Minoru** [comment] 2015-12-19 19:22
Well, since there was no response from the reporter in two weeks, and the issue is probably just a duplicate of #119, I'm closing this. @kozross, feel free to re-open this if building HEAD doesn't fix the issue for you. Thanks!

**Closed by Minoru** 2015-12-19 19:22 UTC
Labels: bug, waiting-for-response
