### ISSUE TITLE
version 2.8 unresponsive on opening big articles with pictures (1.1MB)

### ISSUE THREAD

**Issue by eugenr** [akrennmair/newsbeuter#378] opened 2016-10-17 21:54 UTC
Reproducible using this feed:
http://www.contributors.ro/feed
The article is the one with title starting with "Nicolae Ceausescu...". It contains text and two images. It's URL is: 
http://www.contributors.ro/administratie/nicolae-ceausescu-intre-blocarea-demolarilor-si-rationalizarea-cimentului-1968-1985/

Newsbeuter shows without the problems the list of articles. In this list, the article size is displayed as 1.1MB. Newsbeuter 2.8 becomes unresponsive when trying to open for reading  the article mentioned. I'm sorry, I didn't test with other versions.

On Debian Jessie:
$ newsbeuter -v
Compilation date/time: Sep  2 2014 18:58:01
System: Linux 3.16.0-4-586 (i686)
Compiler: g++ 4.9.1
ncurses: ncurses 5.9.20140913 (compiled with 5.9)
libcurl: libcurl/7.38.0 GnuTLS/3.3.8 zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3 (compiled with 7.37.1)
SQLite: 3.8.7.1 (compiled with 3.8.6)
libxml2: compiled with 2.9.1

**Comment by Minoru** [comment] 2016-10-18 11:06
This is a duplicate of #154, which has been fixed in Newsbeuter 2.9. ;)

**Closed by Minoru** 2016-10-18 11:06 UTC
