### ISSUE TITLE
Screen lag / slow refresh

### ISSUE THREAD

**Issue by supermensa** [akrennmair/newsbeuter#477] opened 2017-01-24 09:40 UTC
**Newsbeuter version (copy from `newsbeuter -v`)**:
newsbeuter 2.9 - http://www.newsbeuter.org/
Copyright (C) 2006-2010 Andreas Krennmair

newsbeuter is free software and licensed under the MIT/X Consortium License.
Type `newsbeuter -vv' for more information.

Compilation date/time: Sep 27 2016 05:30:27
System: Darwin 16.3.0 (x86_64)
Compiler: g++ 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.51.0 SecureTransport zlib/1.2.8 (compiled with 7.49.1)
SQLite: 3.16.2 (compiled with 3.14.2)
libxml2: compiled with 2.9.4

### Problem:
I'm experiencing screen lagging / slow refresh when I'm using Newsbeuter, which means I have to scroll through all feeds to have an updated list on the screen. 

**Example of list at startup**

```
newsbeuter 2.9 - Your feeds (5 unread, 5 total)
2 N (32/52) News B
3 N (8/9) News C
4 N (17/18) News D 
5 N (28/42) News E
```
Title overlapping 1st feed. Then when scrolling the list, there are duplicates.
The highlighted and next item. This happens while scrolling the entire list.

**Example of scrolling a list:**

```
1 N (10/10) News A
2 N (32/52) News B
  3 N (8/9) News C
3 N (8/9) News C
5 N (28/42) News E
```

Problem happens with no config as well as a custom config.
Same thing when browsing an individual feed list.

---
(Thanks for an otherwise great piece of software)

**Comment by Minoru** [comment] 2017-01-24 11:03
Thanks for reporting!

Are you running Newsbeuter inside Tmux, Screen or something like that? What terminal emulator are you using? What does `echo $TERM` print out?

**Comment by Minoru** [comment] 2017-01-24 11:05
Ah, one more thing: does pressing ^L fix the issue?

**Comment by supermensa** [comment] 2017-01-24 16:44
Not inside Tmux or Screen - just default OS X Terminal, the echo output is 'ansi'.
Redrawing the screen with ```^L```does not fix the problem.

I don't have the problem when using [iTerm2](https://github.com/gnachman/iTerm2)

**Comment by Minoru** [comment] 2017-01-24 18:24
Does it work in the default terminal if you run it like this?
```console
$ TERM=xterm-256color newsbeuter
```

How about "xterm" and "screen"?

What does `echo $TERM` say in iTerm2? (Seems such a trivial question, but Google just can't find the answer for me.)

**Comment by mrrcollins** [comment] 2017-01-24 19:19
I can confirm it happens with a terminal type of ansi. If I change Terminal's term type to xterm-color, it shows correctly.

**Comment by supermensa** [comment] 2017-01-25 13:07
@Minoru
Looks like ansi is the problem.

iTerm2 is ```xterm-256color```.
Running Newsbeuter in default terminal with ```TERM=xterm-256color newsbeuter``` fixes it.

**Comment by Minoru** [comment] 2017-01-25 19:03
@supermensa Okay. I don't think this can be fixed in Newsbeuter itself, though: Newsbeuter doesn't look at `TERM` at all; it's probably one of our dependencies (STFL or ncurses) getting confused.

Just add `export TERM=xterm-256color` to your shell's config file, and you should be fine. Would you accept this as a solution?

**Comment by supermensa** [comment] 2017-01-26 14:33
@Minoru I can confirm that changing the settings to xterm-256 colors fixes the problem in OS X default terminal (you can easily change the settings in preferences > advanced)

**Comment by Minoru** [comment] 2017-01-26 16:29
Good! I'll close the issue, then ;)

**Closed by Minoru** 2017-01-26 16:29 UTC
Labels: bug, to-check

**Comment by nabsiddiqui** [comment] 2017-02-04 16:59
I have the same problem.  I can not locate the solution, however.  I use fish shell and using this selected solution in my fish config worked:

'''export TERM=xterm-256color'''

Without the above added, I would receive "xterm-256color" when echoing $TERM.  

For what it is worth, I am using Ubuntu 16.04 with Gnome-terminal.  This is a recent bug that was not an issue in the previous version of newsbeuter.

**Comment by Minoru** [comment] 2017-02-04 17:09
@nabsiddiqui, what does `env | grep TERM` say if you *don't* have the `export` line in your fish shell config?

> For what it is worth, I am using Ubuntu 16.04 with Gnome-terminal. This is a recent bug that was not an issue in the previous version of newsbeuter.

To be clear: you tried 2.8 and 2.9 on the same system and 2.8 behaves properly while 2.9 looks wrong and renders slowly?

**Comment by nabsiddiqui** [comment] 2017-02-04 17:17
The output of that command is TERM=xterm-256color.  Unfortunately, I am not really familiar with which versions worked.  I started receiving this error around a month ago or so if I recall correctly.  I also seem to have issue #246 since around that time.

**Comment by nabsiddiqui** [comment] 2017-02-04 17:22
Also, the screen seems to not resize when changed.  This could be something related to i3 though, which is what I use.  I have to manually go through each of the lists to refresh the output.  This is even with the fish config setting.

**Comment by Minoru** [comment] 2017-02-04 17:40
>  I started receiving this error around a month ago or so if I recall correctly.

So you have version 2.9-3 now? You can check with `apt show newsbeuter`.

> Also, the screen seems to not resize when changed. This could be something related to i3 though

I just played a bit with Newsbeuter 2.9-3 running in Gnome Terminal (`TERM` is `xterm-256color`, the default) in Unity on Ubuntu Xenial (16.04), and resizing works just fine. I highly doubt it has anything to do with the window manager—display-wise, terminal emulator should be the limit of Newsbeuter's world.

If you get a reproducible setup for resizing issue, please open a separate issue.

**Comment by nabsiddiqui** [comment] 2017-02-04 17:59
Yes, I am running 2.9-3 now.  After playing around with it, I think the issue has to do with the terminal rewrapping the name of feeds.  Before, if the title of a feed was very long, it would go off screen.  Now, it goes to the "second line" so to speak.  If the user then resizes the terminal, newsbeuter will still only remember the older size until the user highlights the feed.  Seems to be what is described in #450.

**Comment by nabsiddiqui** [comment] 2017-02-04 18:04
Here are some photos to describe what is happening:
Original:

![screenshot at 2017-02-04 13-01-36](https://cloud.githubusercontent.com/assets/11954508/22620447/549403f2-eada-11e6-9a64-c38903d05888.png)

After resize
![screenshot at 2017-02-04 13-02-12](https://cloud.githubusercontent.com/assets/11954508/22620446/5461c158-eada-11e6-9708-96434a28d0b3.png)

Resize again to maximum screen size:
![screenshot at 2017-02-04 13-02-51](https://cloud.githubusercontent.com/assets/11954508/22620445/545d1824-eada-11e6-88bb-adb07875b1df.png)

**Comment by Minoru** [comment] 2017-02-04 18:11
Okay, okay, I'll file the issue for you. Stop hijacking this one, please.

**Comment by Minoru** [comment] 2017-02-04 18:16
@nabsiddiqui, let's move to #492.
