### ISSUE TITLE
Stackoverflow feeds aren't marked as read in Google Reader

### ISSUE THREAD

**Issue by Donearm** [akrennmair/newsbeuter#30] opened 2012-05-22 13:41 UTC
I've subscribed to a couple of Stackoverflow feeds (like [this](http://stackoverflow.com/feeds/tag?tagnames=lua&sort=newest)) in Google Reader and I can read them fine in Newsbeuter but they don't get marked as read by "mark-feed-read" on Google Reader. Newsbeuter do show them as read, only until next sync when they reappear as new again. Reading every article works correctly (read are indeed marked as read in both Newsbeuter and Reader).

Marking as read in Google Reader is the only way to make them be synced as "read" by Newsbeuter. Other than actually read one by one, that is. It happens only with Stackoverflow feeds, and with any of them.

**Comment by Minoru** [comment] 2015-12-19 23:53
Don't know why I didn't close this a month ago; Google Reader's dead, support for it is dropped, so the issue is irrelevant now. Hope you're still using Newsbeuter, though; and thanks for report! ;)

**Closed by Minoru** 2015-12-19 23:53 UTC
Labels: bug, to-check
