### ISSUE TITLE
Memory leak in v2.8?

### ISSUE THREAD

**Issue by kseistrup** [akrennmair/newsbeuter#119] opened 2014-02-14 08:40 UTC
While I could leave `newsbeuter v2.7` running for weeks, it seems I have to restart `newsbeuter v2.8` at least once a day or it will consume ‘all’ of the machine's memory.

The data in the tables below are compiled from the following shell script:

```sh
while :
do
  ps aux \
  | grep '/usr/local/[b]in/newsbeuter' \
  | timestamp
  sleep 671
done
```

Newsbeuter v2.7 and v2.8 are both running on the same machine (a fairly recent Ubuntu derivative) with the same config, feed list and database. The config is pretty much a default config.  Of relevance to the timing in the tables is `reload-time 53`.

V2.7 and v2.8 are linked to exactly the same libraries, except v2.7 uses `libjson v0.10` (standard Ubuntu) whereas v2.8 uses `libjson-c v0.11` (pulled from the Internet and compiled from source).

The tables (only showing unique lines):

```null
newsbeuter 2.8

YYYY-MM-DD HH:MM:SS	   VSZ	   RSS
==================================
2014-02-13 12:10:50	573940	344604
2014-02-13 12:55:34	639476	388852
2014-02-13 13:40:18	639476	433184
2014-02-13 14:36:13	705012	476152
2014-02-13 15:09:46	712040	483396
2014-02-13 15:32:08	777576	527996
2014-02-13 16:16:52	777576	569004
2014-02-13 16:28:03	777576	574196
2014-02-13 17:01:36	777576	574196
2014-02-13 17:12:47	843112	619076
2014-02-13 17:57:32	843112	618884
2014-02-13 18:08:43	908648	663948
2014-02-13 19:04:38	908648	707072
2014-02-13 19:15:49	916700	711904
```

and in contrast:

```null
newsbeuter 2.7

YYYY-MM-DD HH:MM:SS	   VSZ	   RSS
==================================
2014-02-13 21:07:40	321740	109776
2014-02-13 21:18:51	386248	150048
2014-02-13 21:30:02	398876	157760
2014-02-13 22:14:46	398876	160176
2014-02-13 22:48:19	398876	160160
2014-02-13 23:10:41	398876	160924
2014-02-13 23:55:25	398876	161844
2014-02-14 00:06:36	398876	161792
2014-02-14 00:17:47	398876	161964
2014-02-14 00:51:20	398876	160980
2014-02-14 01:47:16	398876	161964
2014-02-14 02:43:11	398876	160984
2014-02-14 03:27:55	398876	161968
2014-02-14 04:23:50	398876	160980
2014-02-14 05:19:45	398876	161968
2014-02-14 06:15:40	398876	160980
2014-02-14 07:00:24	398876	161868
2014-02-14 07:56:19	398876	160984
```

Cheers.

**Comment by Feandil** [comment] 2015-02-22 11:23
Thanks for releasing newsbeuter 2.9 !
Unfortunately, it seems that the leak is back :(

Before the release I "backported" the fix, @1427bdb0705806368db39576a9b803df82fa0415, on my local 2.8, and that made the leak disappear. The backport was far from perfect as it resulted in various segfaults (I believe when an item was open and the rss was refreshed).

Here is the graph of the RSS used by newsbeuter on my system:
![newsbeuter-2 9](https://cloud.githubusercontent.com/assets/1488247/6318339/101a4120-ba8d-11e4-9d74-7550ae6c6078.jpg)


I'd love to help but I don't really know your code.
Here is the version I'm using:
> newsbeuter 2.9 - http://www.newsbeuter.org/
> Copyright (C) 2006-2010 Andreas Krennmair
> 
> newsbeuter is free software and licensed under the MIT/X Consortium License.
> Type `newsbeuter -vv' for more information.
> 
> Compilation date/time: Feb 21 2015 10:06:06
> System: Linux 3.17.7-hardened-r1 (x86_64)
> Compiler: g++ 4.8.3
> ncurses: ncurses 5.9.20110404 (compiled with 5.9)
> libcurl: libcurl/7.39.0 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.29 (compiled with 7.39.0)
> SQLite: 3.8.7.4 (compiled with 3.8.7.4)
> libxml2: compiled with 2.9.2

**Comment by lucy** [comment] 2015-05-12 09:09
Can reproduce on 2.9.

**Comment by uzsolt** [comment] 2015-07-15 19:19
Me too. It runs about 15 hours and its size is about 1G.

**Comment by Earnestly** [comment] 2015-07-30 12:45
This happens on the latest master at the time of writing (https://github.com/akrennmair/newsbeuter/commit/e425e3e6da0e9ce2c888ed5c972f6da74f0e79b4) and for my feeds it increases in usage by 10M for every refresh of all articles I do without fail.

The increase in memory seems to be closely associated with the loading of new articles (or lack thereof), so while people experience this hike in usage over hours, if you simply refresh the articles constantly, you'll see the same thing very quickly.

**Comment by Minoru** [comment] 2015-11-23 01:11
Can any of you reproduce the issue with current HEAD?

**Comment by Earnestly** [comment] 2015-11-23 01:21
Yes, there is still a leak.  Although it's no where near as severe anymore, from a 10M increase to about 3M per refresh.  Although now and then it actually reduces before doing the refresh, sometimes it doesn't.

Currently from start at around 60M RES, it has increased to 78M.  It seems sometimes release memory and during my limited testing, remains stable between 70M and 78M.

I'll add more after extended use but so far it's looking like a good improvement.

**Comment by Minoru** [comment] 2015-11-23 12:51
That's great! If it's convenient for you, I'd like you to run the test for a while longer—a couple days, I guess—and then report back. Can you?

**Comment by Earnestly** [comment] 2015-11-23 15:46
Very likely, it is still running since I last commented.  Currently it has increased to 114M RES, which is not looking great.  I'll keep it going for a few more days still.

**Comment by Feandil** [comment] 2015-11-24 22:46
Seems also to be way more stable here (on b31ea353c52b9318198154735655160dcfec9dca):
![memory_leak](https://cloud.githubusercontent.com/assets/1488247/11382947/2e2241f8-9305-11e5-9825-d8529dcf272d.png)
(Running for a day with ~70 feeds, reload-time 10)

Thanks for the fix! (there might still be a small leak though...)

**Comment by Earnestly** [comment] 2015-11-24 23:09
Currently 144M RES.

**Comment by Earnestly** [comment] 2015-11-25 23:16
169M RES (+25M)

**Comment by Minoru** [comment] 2015-11-26 05:58
Yup; thank you both for checking. I'm currently trying to pinpoint the problem, will get back to you once I have something to show for it.

**Comment by Feandil** [comment] 2015-11-26 17:36
I left it open (as usual, in a screen) for few days. I didn't have the time to read most of my feeds (didn't touch it much) but it kept running. I don't see the same increase anymore (seem to stabilize after some point?)

Full run:
![newsbeuter-b31ea35](https://cloud.githubusercontent.com/assets/1488247/11428463/14edb22c-946c-11e5-9a3f-b527aa9f15e1.jpg)

Last day:
![newsbeuter-b31ea35-day](https://cloud.githubusercontent.com/assets/1488247/11428499/5b7c1738-946c-11e5-826b-7fbac0d9573b.jpg)

I'll now see if using it more generate more leak ore not.

@Earnestly: these are just the visualisation of some rrd files produced by collectd

**Comment by Minoru** [comment] 2015-11-26 19:33
I've been poking at it with Valgrind (with both memcheck and massif) for the most of today, and I just don't see any real leakage. There *seem* to be a case of strings growing in size, but that might just be new feed items.

Which gives me a thought. @Earnestly, how active are the feeds you're subscribed to? Say, how many new items show up within an hour? On those I'm testing on, I get roughly 10 items per hour. If my thinking about small fluctuations is correct, your feeds must be really active.

@Feandil, I'm very interested in your report. Again, if my thinking is correct, you'll probably experience small dip in the memory usage (because you'll probably delete some items), and then you'll again be experiencing slow rise of used memory as new items are being added.

**Comment by Earnestly** [comment] 2015-11-26 21:55
@Minoru It does vary; it can be between 0 and 10 new entries every 30 minutes based on my highly unscientific observations.

**Comment by Minoru** [comment] 2015-12-13 20:06
Given the feedback from #220, I'm considering this to be fixed and thus closing the issue.

**Closed by Minoru** 2015-12-13 20:06 UTC
Labels: bug, waiting-for-response

**Comment by kozross** [comment] 2016-06-05 09:54
Seems like this bug is still there. Here is the relevant line from my ``top`` command:

```
PID USER   PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND
762 koz       20   0 2040.6m 1.722g   0.0 25.5   2:47.69 S          `- newsbeuter
```

I haven't been running this particular Newsbeuter process very long at all, and it's already eating nearly 2G of RAM.

**Comment by Minoru** [comment] 2016-06-05 10:22
If you built it from Git, `newsbeuter -v` should say it's 2.10. Maybe you've build it but didn't install? You can even run it without installing; just `cd` into the directory where you built it and type `./newsbeuter`.

**Comment by kozross** [comment] 2016-06-05 10:43
@Minoru I got my (installed) Newsbeuter from the [Arch repositories][1]. If it helps any, here's the full output of ``newsbeuter -v``:

```
koz@Sebastian ~ ☛ newsbeuter -v
XDG: configuration directory '/home/koz/.config/newsbeuter' not accessible, using '/home/koz/.newsbeuter' instead.
newsbeuter 2.9 - http://www.newsbeuter.org/
Copyright (C) 2006-2010 Andreas Krennmair

newsbeuter is free software and licensed under the MIT/X Consortium License.
Type `newsbeuter -vv' for more information.

Compilation date/time: Dec  7 2015 04:47:17
System: Linux 4.5.4-gnu-1-pck (x86_64)
Compiler: g++ 5.3.0
ncurses: ncurses 6.0.20150808 (compiled with 6.0)
libcurl: libcurl/7.49.1 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.32 libssh2/1.7.0 (compiled with 7.46.0)
SQLite: 3.13.0 (compiled with 3.9.2)
libxml2: compiled with 2.9.2
```

[1]: https://www.archlinux.org/packages/community/x86_64/newsbeuter/

**Comment by Minoru** [comment] 2016-06-05 10:47
The version you're running is simply too old and doesn't include the fix for the memory leak. You should either clone Git repo and build from source, or wait for 2.10 release.
