### ISSUE TITLE
Bug with item drawing inside tmux

### ISSUE THREAD

**Issue by kurnevsky** [akrennmair/newsbeuter#259] opened 2016-02-01 11:38 UTC
Open attached db, enter to the "Lifehacker" feed and move selection by pressing "down" button. You will see that the item number 61 became same as 62. I can reproduce this only inside tmux (with both versions of newsbeuter: 2.8 and HEAD), it draws correct without tmux.
![1454321834](https://cloud.githubusercontent.com/assets/2943605/12716044/e0163bc0-c8ee-11e5-8dd6-356cf38b835b.png)
[.newsbeuter.zip](https://github.com/akrennmair/newsbeuter/files/112119/default.newsbeuter.zip)

**Comment by Minoru** [comment] 2016-05-29 12:18
Moving this to 2.11 milestone to unblock 2.10 release.

**Comment by orner** [comment] 2016-11-08 03:36
I can't reproduce this in tmux and newsbeuter 2.9 or 2.10(HEAD), although I seem to recall having a this problem previously.  Is this still a problem in the latest version of newsbeuter?

**Comment by kurnevsky** [comment] 2016-11-10 06:09
Neither can I. Perhaps it was fixed with tmux update.

**Comment by Minoru** [comment] 2016-11-10 19:22
…but I can.

The title of this item contains a soft hyphen, which seem to break either STFL or Ncurses. We actually [remove them](https://github.com/akrennmair/newsbeuter/commit/1addb6188179786bb5ba660665235aa5714a6f77), but only from HTML; titles aren't passed through that module. This is related to #237; I should probably re-consider my decision on that issue.

**Closed** 2016-11-23 23:25 UTC
Labels: bug
