### ISSUE TITLE
Split panel

### ISSUE THREAD

**Issue by gtr6ytuuygf** [akrennmair/newsbeuter#530] opened 2017-04-07 06:32 UTC
When I enter a feed (where I get the list with all articles) it would be very useful to have the window split in 2 with the list of articles in one hand and the view of the selected article on the other side. Like this

```
+----------------------------------+
|  Article 1                       |
|  Article 2                       |
|  ....                            |
+----------------------------------+
|  article                         |
|        content                   |
|               here               |
+--------------------------------- +
```

I couldn't find any setting for this.

**Comment by kyyu** [comment] 2017-04-07 16:12
#461 albeit a different view

**Comment by Minoru** [comment] 2017-04-08 12:52
The general idea is the same, so I think it counts as a duplicate of #461.

**Closed by Minoru** 2017-04-08 12:52 UTC
