### ISSUE TITLE
Empty articles global feed update

### ISSUE THREAD

**Issue by SiIky** [akrennmair/newsbeuter#498] opened 2017-02-08 15:17 UTC
**Newsbeuter version (copy from `newsbeuter -v`)**:

newsbeuter 2.9 - http://www.newsbeuter.org/
Copyright (C) 2006-2010 Andreas Krennmair

newsbeuter is free software and licensed under the MIT/X Consortium License.
Type `newsbeuter -vv' for more information.

System: Linux 3.16.0-4-amd64 (x86_64)
Compiler: g++ 6.2.1 20161215
ncurses: ncurses 6.0.20161126 (compiled with 6.0)
libcurl: libcurl/7.52.1 GnuTLS/3.5.8 zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3 (compiled
with 7.51.0)
SQLite: 3.16.2 (compiled with 3.15.2)
libxml2: compiled with 2.9.4

Steps to reproduce the issue:

1. Add feeds to the `urls` file
2. Open newsbeuter (with the option to update feeds at start or after hitting `R`)
3. Open a feed and article while newbeuter updates the feeds
4. Wait for newsbeuter to finish updating the feeds

**Other info you think is relevant**:

When newsbeuter finishes updating the feeds, the open article is turned "blank", with (what seems to be) garbage from memory.
If I hit `q` to close the article, it goes back to the article list for that feed, as it should, and the article is still marked as new.

I'm using the version from the testing branch of Debian (Stretch).

While updating:
![Reflex feed](https://i.imgur.com/3iVvlL9.png)
After updating:
![Reflex feed](https://i.imgur.com/KxjRpN6.png)

While updating:
![250bpm feed](https://i.imgur.com/VyeAwbm.png)
After updating:
![250bpm feed](https://i.imgur.com/VrhM8rH.png)

**EDIT: TL;DR:** A bug, but not a big scary one, more like a ladybug.

**Comment by Minoru** [comment] 2017-02-08 17:50
This is a duplicate of #223, so I'm going to close it. Thanks for a nice report though.

**Closed by Minoru** 2017-02-08 17:50 UTC

**Comment by SiIky** [comment] 2017-02-08 23:08
@Minoru Ah I searched for different keywords, that's why I couldn't find it. Sorry for the trouble!
