### ISSUE TITLE
URLs tree

### ISSUE THREAD

**Issue by gtr6ytuuygf** [akrennmair/newsbeuter#529] opened 2017-04-07 06:28 UTC
Would be nice to have a way to group URLs into "folders", like a tree. Very useful when there are hundreds of feeds.

**Comment by kyyu** [comment] 2017-04-07 16:11
#487

Randomly decided to check this project and you've brought up both my ideal features for newsbeuter. Are you an QuiteRSS/RSSowl user looking for a new client?

**Comment by gtr6ytuuygf** [comment] 2017-04-07 17:56
> Are you an QuiteRSS/RSSowl user looking for a new client?

Nope, just a command line lover who likes clean interfaces :)

**Comment by Minoru** [comment] 2017-04-08 12:50
Just as @kyyu points out, this is a duplicate of #487.

**Closed by Minoru** 2017-04-08 12:50 UTC
