### ISSUE TITLE
Text hidden

### ISSUE THREAD

**Issue by antoyo** [akrennmair/newsbeuter#541] opened 2017-04-27 03:56 UTC
**Newsbeuter version (copy from `newsbeuter -v`)**:
```
newsbeuter 2.9 - http://www.newsbeuter.org/
Copyright (C) 2006-2010 Andreas Krennmair

newsbeuter est un logiciel libre, publié sous licence MIT/X Consortium.
Tapez `newsbeuter -vv' pour obtenir plus d'informations.

Compilation date/time: Mar  8 2017 21:56:57
System: Linux 4.10.11-1-ARCH (x86_64)
Compiler: g++ 6.3.1 20170306
ncurses: ncurses 6.0.20170401 (compiled with 6.0)
libcurl: libcurl/7.54.0 OpenSSL/1.1.0e zlib/1.2.11 libpsl/0.17.0 (+libicu/58.2) libssh2/1.8.0 (compiled with 7.53.1)
SQLite: 3.18.0 (compiled with 3.17.0)
libxml2: compiled with 2.9.4
```

Steps to reproduce the issue:

1. (Same issue without config.)
2. Add multiple URLs in the `urls` file.
3. Navigate in the threads

I cannot see the text, except for the selected items, in all views.

**Other info you think is relevant**:
That seems to be broken since an update.
I tried multiple terminals and they all have the same issue.
Screenshot: 
![img-2017-04-26-235453](https://cloud.githubusercontent.com/assets/584972/25467387/d6ca390e-2adb-11e7-84bb-33efc4688f4f.png)
Thanks to fix this issue.

**Comment by frifix** [comment] 2017-04-27 09:02
The problem is with ncurses since version 6.0.20170401. I have checked a most recent version 6.0.20170422, but there the problem still persist. I have compiled and installed previous version 6.0.20170128 and everything works. Everything indicates that there is a problem with ncurses.

**Comment by Minoru** [comment] 2017-04-27 17:30
This is a duplicate of #528. Thanks for the reporting though!

**Closed by Minoru** 2017-04-27 17:30 UTC
